### ISSUE TITLE
Disallow 3.x failures on Travis when 3.x is actually passing

### ISSUE THREAD

**Issue by eteq** [astropy/halotools#266]
As discussed in #253, currently on Travis the 3.x builds are being run but allowed to fail.  Once 3.x compatibility is in, that should be changed so that failing 3.x builds fail the whole travis run (and, more importantly, make the merge button red instead of green...).

All that's necessary to accomplish this is going into the ``.travis.yml`` file and removing the part that says this:
```
    allow_failures:
        - python: 3.3
        - python: 3.4
        - python: 3.5
```
